### PR TITLE
upgrade okhttp_ws to 2.4.0

### PR DESCRIPTION
**Pull request by b95505017**

### CODE REVIEW

**Comment by nkzawa** [comment]
thx!

**Comment by b95505017** [comment]
Glad to see it help some issue.
Any plan about the new release? :smile:

**Comment by nkzawa** [comment]
I have no specific plan, but will release it asap if required.

**Comment by b95505017** [comment]
It looks like #19 not an issue, we never use OkHttp 2.4-RC.

**Comment by niqo01** [comment]
@nkzawa The Square folks told me to hold off using WebSocket with OkHttp 2.3 until 2.4 is out due to the Websocket fixes in 2.4:
```
Fix: Websockets no longer rebuffer socket streams.
Fix: Websockets are now better at handling close frames.
```
Just sharing.

**Comment by b95505017** [comment]
OkHttp 2.4 is out last week.

**Pull request merged**
